
import pandas as pd
from market_estimation_engine import MarketEstimationEngine, EstimationComponent

def generate_audit_component_html(engine: MarketEstimationEngine, best_comp: EstimationComponent, facts_manager, scope_details=None):
    """
    Génère le composant 'Analyse Méthodologique Détaillée' (Audit Log).
    Structure en 8 sections repliables.
    """
    
    # --- HELPER CSS ---
    # Nous injecterons du CSS spécifique pour les sections 'details' / 'summary'
    audit_css = """
    <style>
        .audit-container { font-family: 'Inter', sans-serif; color: #E0E0E0; max-width: 100%; margin-top:20px; }
        .audit-section { margin-bottom: 20px; background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.1); border-radius: 8px; overflow: hidden; }
        .audit-summary { 
            padding: 15px; cursor: pointer; background: rgba(255,255,255,0.05); font-weight: 600; font-size: 1.1em; color: #BBDEFB;
            display: flex; justify-content: space-between; align-items: center;
        }
        .audit-summary:hover { background: rgba(255,255,255,0.08); }
        .audit-content { padding: 20px; border-top: 1px solid rgba(255,255,255,0.1); display: block; }
        
        .audit-tag { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.8em; margin-right: 5px; font-weight: bold; }
        .tag-info { background: #0288D1; color: white; }
        .tag-success { background: #388E3C; color: white; }
        .tag-warning { background: #FBC02D; color: black; }
        .tag-critical { background: #D32F2F; color: white; }
        
        .fact-table { width: 100%; border-collapse: collapse; font-size: 0.9em; }
        .fact-table th { text-align: left; padding: 8px; border-bottom: 1px solid #444; color: #90CAF9; }
        .fact-table td { padding: 8px; border-bottom: 1px solid #333; }
        
        .calc-step { margin-bottom: 10px; font-family: monospace; background: rgba(0,0,0,0.3); padding: 8px; border-left: 3px solid #0091DA; }
    </style>
    <div class="audit-container">
    """
    
    # --- DATA PREPARATION ---
    # 1. Trigger & Scope
    scope_fact = facts_manager.get_fact_value("market_scope", "N/A")
    scope_industry = facts_manager.get_fact_value("industry", "N/A") # Assuming we saved these separately or parse scope string
    
    # 2. Method Selection
    estimations = engine.get_all_estimations()
    
    # 3. Facts (All)
    all_facts_df = facts_manager.get_all_facts_as_dataframe()
    facts_count = len(all_facts_df) if not all_facts_df.empty else 0
    
    # --- GENERATION HTML (SECTIONS) ---
    
    html = audit_css
    
    # 1️⃣ Déclenchement & Compréhension (Scope)
    html += f"""
    <details class="audit-section" open>
        <summary class="audit-summary">
            <span>1️⃣ Déclenchement & Périmètre</span>
            <span class="audit-tag tag-info">Scope Interprété</span>
        </summary>
        <div class="audit-content">
            <p>L'agent a interprété la requête utilisateur et défini le périmètre d'analyse suivant :</p>
            <ul>
                <li><b>Périmètre Global :</b> {scope_fact}</li>
                <!-- We could refine this if we had structured scope variables -->
            </ul>
        </div>
    </details>
    """
    
    # 2️⃣ Choix de la Méthode
    # Build Method Comparison Table
    meth_rows = ""
    for comp in estimations:
        status_icon = "✅" if comp.status == "complete" else "⚠️"
        is_selected = " (RETENU)" if comp.id == best_comp.id else ""
        row_style = "background: rgba(76, 175, 80, 0.1);" if comp.id == best_comp.id else ""
        
        meth_rows += f"""
        <tr style="{row_style}">
            <td>{status_icon} <b>{comp.name}</b>{is_selected}</td>
            <td>{comp.confidence.upper()}</td>
            <td>{comp.missing_data_strategy if comp.status != "complete" else "Complet"}</td>
        </tr>
        """

    html += f"""
    <details class="audit-section">
        <summary class="audit-summary">
            <span>2️⃣ Choix de la Méthode d'Estimation</span>
            <span class="audit-tag tag-success">{best_comp.name}</span>
        </summary>
        <div class="audit-content">
            <p>Le système a évalué {len(estimations)} stratégies possibles. La méthode <b>{best_comp.name}</b> a été retenue car elle présentait le meilleur compromis Complétude / Confiance.</p>
            <table class="fact-table">
                <thead><tr><th>Méthode</th><th>Confiance</th><th>Statut / Raison</th></tr></thead>
                <tbody>{meth_rows}</tbody>
            </table>
        </div>
    </details>
    """
    
    # 3️⃣ Requêtes (Journal de bord - Simulé pour l'instant)
    # Since we can't easily access the exact previous queries here in statutory way without logging,
    # we represent the 'Need' generated by the methods.
    
    queries_html = ""
    for comp in estimations:
        queries_html += f"<li>Recherche de données pour <b>{comp.name}</b>... <span style='color:#888'>[Simulé: Moteur de recherche Mistral activé]</span></li>"
        
    html += f"""
    <details class="audit-section">
        <summary class="audit-summary">
            <span>3️⃣ Journal de Recherche (Requêtes)</span>
            <span class="audit-tag tag-info">Log IA</span>
        </summary>
        <div class="audit-content">
            <p>Recherches effectuées par l'agent pour satisfaire les méthodes :</p>
            <ul>{queries_html}</ul>
        </div>
    </details>
    """
    
    # 4️⃣ Facts Collectés
    # Table of facts used by the BEST method
    used_facts_rows = ""
    if best_comp.data_used:
        for f in best_comp.data_used:
             src_type = f.get("source_type", "Standard")
             badge_cls = "tag-warning" if src_type in ["Proxy", "Estimation"] else "tag-success"
             
             used_facts_rows += f"""
             <tr>
                <td><code>{f.get('key')}</code></td>
                <td><b>{f.get('value')}</b> {f.get('unit')}</td>
                <td><span class="audit-tag {badge_cls}">{src_type}</span></td>
                <td>{f.get('source')}</td>
             </tr>
             """
    else:
        used_facts_rows = "<tr><td colspan='4'>Aucune donnée spécifique utilisée (Méthode vide)</td></tr>"

    html += f"""
    <details class="audit-section">
        <summary class="audit-summary">
            <span>4️⃣ Facts Actifs (Données du Calcul)</span>
            <span class="audit-tag tag-info">{len(best_comp.data_used)} Facts Utilisés</span>
        </summary>
        <div class="audit-content">
            <p>Données atomiques extraites et validées pour ce calcul :</p>
            <table class="fact-table">
                <thead><tr><th>Variable</th><th>Valeur</th><th>Type</th><th>Source</th></tr></thead>
                <tbody>{used_facts_rows}</tbody>
            </table>
            <div style="margin-top:10px; font-size:0.8em; color:#888;">
                * Voir le tableau complet en bas de page pour l'ensemble des données récoltées.
            </div>
        </div>
    </details>
    """
    
    # 5️⃣ Hypothèses et Approximations
    # Filter for Proxy/Estimation in best comp
    proxies = [f for f in best_comp.data_used if f.get("source_type") in ["Proxy", "Estimation", "Interne"]]
    proxies_html = ""
    if proxies:
        for p in proxies:
             proxies_html += f"<li><b>{p.get('key')}</b> a été approximé ({p.get('source_type')}). <i>Raison: Donnée directe non disponible ou confidentielle.</i></li>"
    else:
        proxies_html = "<li>Aucune approximation majeure. Données primaires disponibles.</li>"

    html += f"""
    <details class="audit-section">
        <summary class="audit-summary">
            <span>5️⃣ Hypothèses & Approximations</span>
            <span class="audit-tag tag-warning">{len(proxies)} Proxies</span>
        </summary>
        <div class="audit-content">
            <ul>{proxies_html}</ul>
        </div>
    </details>
    """
    
    # 6️⃣ Logique de Calcul
    html += f"""
    <details class="audit-section" open>
        <summary class="audit-summary">
            <span>6️⃣ Formule & Calcul</span>
            <span class="audit-tag tag-success">Audit Mathématique</span>
        </summary>
        <div class="audit-content">
            <p>Détail de l'opération finale :</p>
            <div class="calc-step">
                Stratégie : {best_comp.selected_strategy_name}
            </div>
            <div class="calc-step">
                {best_comp.calculation_breakdown}
            </div>
            <!-- If we had intermediate steps object, we would list them here -->
            <div class="calc-step" style="border-left-color: #4CAF50; font-weight:bold;">
                 = {best_comp.estimated_value:,.0f} € (Résultat Final)
            </div>
        </div>
    </details>
    """

    # 7️⃣ Triangulation & Contrôle
    # Compare with other methods results if available
    comparison_html = ""
    valid_others = [c for c in estimations if c.id != best_comp.id and c.estimated_value is not None and c.estimated_value > 0]
    
    if valid_others:
        for other in valid_others:
            diff_pct = ((other.estimated_value - best_comp.estimated_value) / best_comp.estimated_value) * 100
            diff_str = f"+{diff_pct:.1f}%" if diff_pct > 0 else f"{diff_pct:.1f}%"
            comparison_html += f"<li>Vs <b>{other.name}</b> ({other.estimated_value:,.0f} €) : Écart de <b>{diff_str}</b>.</li>"
    else:
        comparison_html = "<li>Pas d'autres estimations complètes pour comparaison (Triangulation impossible).</li>"

    html += f"""
    <details class="audit-section">
        <summary class="audit-summary">
            <span>7️⃣ Contrôle de Cohérence (Cross-Check)</span>
        </summary>
        <div class="audit-content">
            <ul>{comparison_html}</ul>
        </div>
    </details>
    """
    
    # 8️⃣ Limites
    html += f"""
    <details class="audit-section">
        <summary class="audit-summary">
            <span>8️⃣ Limites & Confiance</span>
            <span class="audit-tag tag-{ 'success' if best_comp.confidence == 'high' else 'warning'}">{best_comp.confidence.upper()}</span>
        </summary>
        <div class="audit-content">
            <p>Le niveau de confiance est <b>{best_comp.confidence.upper()}</b>.</p>
            <p>Limites identifiées :</p>
            <ul>
                <li>La fraîcheur des données dépend des sources citées (voir section 4).</li>
                <li>Les proxies (section 5) introduisent une marge d'erreur.</li>
            </ul>
        </div>
    </details>
    """
    
    html += "</div>"
    return html
